version: "3.8"
services:
  postgres:
    container_name: postgres
    build: ../app02
    environment:
      POSTGRES_PASSWORD: "mysecret"
    networks:
      - backend
  
  adminer:
    image: adminer
    depends_on:
      - postgres
    networks:
      - backend
    ports: 
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "postgres"
  
  worker:
    depends_on:
      - postgres
    build: ../app05
    networks:
      - backend
      - frontend
    environment:
      dbserver: "postgres"
      dbname: "app"
      dbuser: "postgres"
      dbpassword: "mysecret"
      interval: 4
    deploy:
      replicas: 2

  nginx:
    depends_on:
      - worker
    networks:
      - frontend
    image: nginx
    volumes:
      - "$PWD/proxy2.conf:/etc/nginx/conf.d/nginx.conf"
    ports:
      - "8081:8081"

networks:
  frontend:
  backend:
