$node1_ip = "192.168.0.51"
$node1_name = "hmdck01"
$node2_ip = "192.168.0.52"
$node2_name = "hmdck02"
$k8s_ip = "192.168.0.53"
$k8s_name = "hmkbs01"
$pod_network = "10.244.0.0/16"

$install_git = <<-'SCRIPT'
sudo yum install -y git
SCRIPT


$install_docker = <<-'SCRIPT'
sudo yum install -y yum-utils
sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
sudo yum -y install docker-ce docker-ce-cli containerd.io
sudo systemctl start docker
sudo systemctl enable docker
SCRIPT

$kubernetes_prerequisites = <<-'SCRIPT'
setenforce 0
sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
modprobe br_netfilter
sed -i --follow-symlinks 's/net.bridge.bridge-nf-call-ip6tables = 0/net.bridge.bridge-nf-call-iptables = 1/g' /usr/lib/sysctl.d/00-system.conf
sed -i --follow-symlinks 's/net.bridge.bridge-nf-call-iptables = 0/net.bridge.bridge-nf-call-iptables = 1/g' /usr/lib/sysctl.d/00-system.conf
sed -i --follow-symlinks 's/net.bridge.bridge-nf-call-arptables = 0/net.bridge.bridge-nf-call-arptables = 1/g' /usr/lib/sysctl.d/00-system.conf
echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
echo '1' > /proc/sys/net/ipv4/ip_forward
swapoff -a
sed -i '/swap/d' /etc/fstab
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[Kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
yum install kubeadm -y
systemctl start docker.service
systemctl enable docker.service
systemctl enable kubelet
SCRIPT

$install_k8s = <<-SCRIPT
mkdir -p ~/.ssh
ssh-keyscan -H #{$node1_ip} >> /home/vagrant/.ssh/known_hosts
ssh-keyscan -H #{$node2_ip} >> /home/vagrant/.ssh/known_hosts
cp /home/vagrant/.ssh/id_rsa /root/.ssh/
cp /home/vagrant/.ssh/known_hosts /root/.ssh/known_hosts

kubeadm init --apiserver-advertise-address=#{$k8s_ip} --pod-network-cidr=#{$pod_network}
export KUBECONFIG=/etc/kubernetes/admin.conf
echo 'export KUBECONFIG=/etc/kubernetes/admin.conf' >> /root/.bashrc
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
token=`kubeadm token create`
hash=`openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | \
   openssl dgst -sha256 -hex | sed 's/^.* //'`
ssh vagrant@#{$node1_ip} sudo kubeadm join --token ${token} #{$k8s_ip}:6443 --discovery-token-ca-cert-hash sha256:${hash}
ssh vagrant@#{$node2_ip} sudo kubeadm join --token ${token} #{$k8s_ip}:6443 --discovery-token-ca-cert-hash sha256:${hash}
SCRIPT

### N O D E 1 ###

Vagrant.configure("2") do |config|
  config.vm.define $node1_name do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = $node1_name
    config.vm.network "public_network", ip: $node1_ip
    config.vm.provision "shell", inline: $install_git
    config.vm.provision "shell", inline: $install_docker
    config.vm.provision "shell", inline: $kubernetes_prerequisites
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    config.vm.provision :shell, :inline =>"
     echo 'Copying public SSH Keys to the VM'
     mkdir -p /home/vagrant/.ssh
     chmod 700 /home/vagrant/.ssh
     echo '#{ssh_pub_key}' >> /home/vagrant/.ssh/authorized_keys
     chmod -R 600 /home/vagrant/.ssh/authorized_keys
     echo 'Host 192.168.*.*' >> /home/vagrant/.ssh/config
     echo 'StrictHostKeyChecking no' >> /home/vagrant/.ssh/config
     echo 'UserKnownHostsFile /dev/null' >> /home/vagrant/.ssh/config
     chmod -R 600 /home/vagrant/.ssh/config
     ", privileged: false
  end
end

### N O D E 1 end ###


### N O D E 2 ###

Vagrant.configure("2") do |config|
  config.vm.define $node2_name do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = $node2_name
    config.vm.network "public_network", ip: $node2_ip
    config.vm.provision "shell", inline: $install_git
    config.vm.provision "shell", inline: $install_docker
    config.vm.provision "shell", inline: $kubernetes_prerequisites
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    config.vm.provision :shell, :inline =>"
     echo 'Copying public SSH Keys to the VM'
     mkdir -p /home/vagrant/.ssh
     chmod 700 /home/vagrant/.ssh
     echo '#{ssh_pub_key}' >> /home/vagrant/.ssh/authorized_keys
     chmod -R 600 /home/vagrant/.ssh/authorized_keys
     echo 'Host 192.168.*.*' >> /home/vagrant/.ssh/config
     echo 'StrictHostKeyChecking no' >> /home/vagrant/.ssh/config
     echo 'UserKnownHostsFile /dev/null' >> /home/vagrant/.ssh/config
     chmod -R 600 /home/vagrant/.ssh/config
     ", privileged: false
  end
end

### N O D E 2 end ###


### K 8 S ###

Vagrant.configure("2") do |config|
  config.vm.define $k8s_name do |config|
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "2048"
    end
    config.vm.box = "centos/7"
    config.vm.hostname = $k8s_name
    config.vm.network "public_network", ip: $k8s_ip
    config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
    config.vm.provision "shell", inline: $install_git
    config.vm.provision "shell", inline: $install_docker
    config.vm.provision "shell", inline: $kubernetes_prerequisites
    config.vm.provision "shell", inline: $install_k8s
  end
end

### K 8 S end ###
