version: "3.8"
services:
  postgres:
    container_name: postgres
    build: ../app02
    environment:
      POSTGRES_PASSWORD: "mysecret"
    networks:
      - backend
  
  adminer:
    image: adminer
    depends_on:
      - postgres
    networks:
      - backend
    ports: 
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "postgres"
  
  worker:
    depends_on:
      - postgres
    build: ../app05
    networks:
      - backend
    environment:
      dbserver: "postgres"
      dbname: "app"
      dbuser: "postgres"
      dbpassword: "mysecret"
      interval: 4
    deploy:
      replicas: 2

  web:
    depends_on:
      - postgres
    build: ../app05
    networks:
      - backend
    environment:
      dbserver: "postgres"
      dbname: "app"
      dbuser: "postgres"
      dbpassword: "mysecret"
      interval: 4
    ports:
      - "80:80"
networks:
  backend:
